### ISSUE TITLE
Link in read me gives 404

### ISSUE THREAD

**Issue by bryantaustin13** [cqframework/cqf#7]
The link http://build.fhir.org/ig/cqframework/cqf returns a 404. http://build.fhir.org/ig/cqframework/cqf-us/ Does resolve to a viable site.

**Comment by bryantaustin13** [comment]
See https://github.com/cqframework/cqf/pull/8#issue-1922297772 for fix.

**Comment by brynrhodes** [comment]
The link is a 404 because the site has been cleared (the ci build site is temporary), the fix is to bump the build
